# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from com_csaa_claims_ai_assignment.models.base_model_ import Model
from com_csaa_claims_ai_assignment.models.ai_result import AIResult
from com_csaa_claims_ai_assignment.models.api_processing_response_metadata import ApiProcessingResponseMetadata
from com_csaa_claims_ai_assignment.models.claim import Claim
from com_csaa_claims_ai_assignment.models.response import Response
from com_csaa_claims_ai_assignment import util

from com_csaa_claims_ai_assignment.models.ai_result import AIResult  # noqa: E501
from com_csaa_claims_ai_assignment.models.api_processing_response_metadata import ApiProcessingResponseMetadata  # noqa: E501
from com_csaa_claims_ai_assignment.models.claim import Claim  # noqa: E501
from com_csaa_claims_ai_assignment.models.response import Response  # noqa: E501

class ApiProcessingResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, api_request_raw=None, api_response_raw=None, api_request_processed=None, ai_model_details=None, metadata=None):  # noqa: E501
        """ApiProcessingResponse - a model defined in OpenAPI

        :param api_request_raw: The api_request_raw of this ApiProcessingResponse.  # noqa: E501
        :type api_request_raw: Claim
        :param api_response_raw: The api_response_raw of this ApiProcessingResponse.  # noqa: E501
        :type api_response_raw: Response
        :param api_request_processed: The api_request_processed of this ApiProcessingResponse.  # noqa: E501
        :type api_request_processed: str
        :param ai_model_details: The ai_model_details of this ApiProcessingResponse.  # noqa: E501
        :type ai_model_details: List[AIResult]
        :param metadata: The metadata of this ApiProcessingResponse.  # noqa: E501
        :type metadata: ApiProcessingResponseMetadata
        """
        self.openapi_types = {
            'api_request_raw': Claim,
            'api_response_raw': Response,
            'api_request_processed': str,
            'ai_model_details': List[AIResult],
            'metadata': ApiProcessingResponseMetadata
        }

        self.attribute_map = {
            'api_request_raw': 'api_request_raw',
            'api_response_raw': 'api_response_raw',
            'api_request_processed': 'api_request_processed',
            'ai_model_details': 'ai_model_details',
            'metadata': 'metadata'
        }

        self._api_request_raw = api_request_raw
        self._api_response_raw = api_response_raw
        self._api_request_processed = api_request_processed
        self._ai_model_details = ai_model_details
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'ApiProcessingResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiProcessingResponse of this ApiProcessingResponse.  # noqa: E501
        :rtype: ApiProcessingResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_request_raw(self):
        """Gets the api_request_raw of this ApiProcessingResponse.


        :return: The api_request_raw of this ApiProcessingResponse.
        :rtype: Claim
        """
        return self._api_request_raw

    @api_request_raw.setter
    def api_request_raw(self, api_request_raw):
        """Sets the api_request_raw of this ApiProcessingResponse.


        :param api_request_raw: The api_request_raw of this ApiProcessingResponse.
        :type api_request_raw: Claim
        """

        self._api_request_raw = api_request_raw

    @property
    def api_response_raw(self):
        """Gets the api_response_raw of this ApiProcessingResponse.


        :return: The api_response_raw of this ApiProcessingResponse.
        :rtype: Response
        """
        return self._api_response_raw

    @api_response_raw.setter
    def api_response_raw(self, api_response_raw):
        """Sets the api_response_raw of this ApiProcessingResponse.


        :param api_response_raw: The api_response_raw of this ApiProcessingResponse.
        :type api_response_raw: Response
        """

        self._api_response_raw = api_response_raw

    @property
    def api_request_processed(self):
        """Gets the api_request_processed of this ApiProcessingResponse.


        :return: The api_request_processed of this ApiProcessingResponse.
        :rtype: str
        """
        return self._api_request_processed

    @api_request_processed.setter
    def api_request_processed(self, api_request_processed):
        """Sets the api_request_processed of this ApiProcessingResponse.


        :param api_request_processed: The api_request_processed of this ApiProcessingResponse.
        :type api_request_processed: str
        """

        self._api_request_processed = api_request_processed

    @property
    def ai_model_details(self):
        """Gets the ai_model_details of this ApiProcessingResponse.


        :return: The ai_model_details of this ApiProcessingResponse.
        :rtype: List[AIResult]
        """
        return self._ai_model_details

    @ai_model_details.setter
    def ai_model_details(self, ai_model_details):
        """Sets the ai_model_details of this ApiProcessingResponse.


        :param ai_model_details: The ai_model_details of this ApiProcessingResponse.
        :type ai_model_details: List[AIResult]
        """

        self._ai_model_details = ai_model_details

    @property
    def metadata(self):
        """Gets the metadata of this ApiProcessingResponse.


        :return: The metadata of this ApiProcessingResponse.
        :rtype: ApiProcessingResponseMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this ApiProcessingResponse.


        :param metadata: The metadata of this ApiProcessingResponse.
        :type metadata: ApiProcessingResponseMetadata
        """

        self._metadata = metadata
