# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from com_csaa_claims_ai_assignment.models.base_model_ import Model
from com_csaa_claims_ai_assignment import util


class Fault(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, http_code=None, http_message=None, more_information=None, time_stamp=None):  # noqa: E501
        """Fault - a model defined in OpenAPI

        :param http_code: The http_code of this Fault.  # noqa: E501
        :type http_code: str
        :param http_message: The http_message of this Fault.  # noqa: E501
        :type http_message: str
        :param more_information: The more_information of this Fault.  # noqa: E501
        :type more_information: str
        :param time_stamp: The time_stamp of this Fault.  # noqa: E501
        :type time_stamp: str
        """
        self.openapi_types = {
            'http_code': str,
            'http_message': str,
            'more_information': str,
            'time_stamp': str
        }

        self.attribute_map = {
            'http_code': 'httpCode',
            'http_message': 'httpMessage',
            'more_information': 'moreInformation',
            'time_stamp': 'timeStamp'
        }

        self._http_code = http_code
        self._http_message = http_message
        self._more_information = more_information
        self._time_stamp = time_stamp

    @classmethod
    def from_dict(cls, dikt) -> 'Fault':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Fault of this Fault.  # noqa: E501
        :rtype: Fault
        """
        return util.deserialize_model(dikt, cls)

    @property
    def http_code(self):
        """Gets the http_code of this Fault.


        :return: The http_code of this Fault.
        :rtype: str
        """
        return self._http_code

    @http_code.setter
    def http_code(self, http_code):
        """Sets the http_code of this Fault.


        :param http_code: The http_code of this Fault.
        :type http_code: str
        """

        self._http_code = http_code

    @property
    def http_message(self):
        """Gets the http_message of this Fault.


        :return: The http_message of this Fault.
        :rtype: str
        """
        return self._http_message

    @http_message.setter
    def http_message(self, http_message):
        """Sets the http_message of this Fault.


        :param http_message: The http_message of this Fault.
        :type http_message: str
        """

        self._http_message = http_message

    @property
    def more_information(self):
        """Gets the more_information of this Fault.


        :return: The more_information of this Fault.
        :rtype: str
        """
        return self._more_information

    @more_information.setter
    def more_information(self, more_information):
        """Sets the more_information of this Fault.


        :param more_information: The more_information of this Fault.
        :type more_information: str
        """

        self._more_information = more_information

    @property
    def time_stamp(self):
        """Gets the time_stamp of this Fault.


        :return: The time_stamp of this Fault.
        :rtype: str
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp):
        """Sets the time_stamp of this Fault.


        :param time_stamp: The time_stamp of this Fault.
        :type time_stamp: str
        """

        self._time_stamp = time_stamp
