# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from com_csaa_claims_ai_assignment.models.base_model_ import Model
from com_csaa_claims_ai_assignment.models.ai_result import AIResult
from com_csaa_claims_ai_assignment import util

from com_csaa_claims_ai_assignment.models.ai_result import AIResult  # noqa: E501

class Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, group_type=None, results=None):  # noqa: E501
        """Response - a model defined in OpenAPI

        :param group_type: The group_type of this Response.  # noqa: E501
        :type group_type: str
        :param results: The results of this Response.  # noqa: E501
        :type results: List[AIResult]
        """
        self.openapi_types = {
            'group_type': str,
            'results': List[AIResult]
        }

        self.attribute_map = {
            'group_type': 'groupType',
            'results': 'results'
        }

        self._group_type = group_type
        self._results = results

    @classmethod
    def from_dict(cls, dikt) -> 'Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Response of this Response.  # noqa: E501
        :rtype: Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def group_type(self):
        """Gets the group_type of this Response.


        :return: The group_type of this Response.
        :rtype: str
        """
        return self._group_type

    @group_type.setter
    def group_type(self, group_type):
        """Sets the group_type of this Response.


        :param group_type: The group_type of this Response.
        :type group_type: str
        """

        self._group_type = group_type

    @property
    def results(self):
        """Gets the results of this Response.


        :return: The results of this Response.
        :rtype: List[AIResult]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this Response.


        :param results: The results of this Response.
        :type results: List[AIResult]
        """

        self._results = results
